#!/usr/bin/env python3
# Bakes DejaVu Sans Condensed Bold (Bitstream Vera licence, free to embed)
# into antialiased alpha atlases for ASCII 32..126 at several pixel sizes.
# Output: src/engine/font_atlas.h
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = '/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf'
SIZES = [9, 11, 13, 15, 18, 22]   # line heights in pixels
out = sys.argv[1] if len(sys.argv) > 1 else 'src/engine/font_atlas.h'

lines = ['// Generated by tools/make_font.py from DejaVu Sans Condensed Bold.',
         '// DejaVu fonts: Bitstream Vera licence (free use and embedding).',
         '#pragma once', '#include <cstdint>', '', 'namespace swgb::font {', '',
         'struct Glyph { uint16_t x, y; uint8_t w, h; int8_t xoff, yoff; uint8_t advance; };',
         'struct Face { int lineHeight, ascent, atlasW, atlasH; const Glyph *glyphs; const uint8_t *alpha; };', '']
faces = []
for size in SIZES:
    # pick a point size whose ascent+descent ~= line height
    pt = size
    while pt > 4:
        f = ImageFont.truetype(FONT, pt)
        a, d = f.getmetrics()
        if a + d <= size + 1: break
        pt -= 1
    f = ImageFont.truetype(FONT, pt)
    ascent, descent = f.getmetrics()
    glyphs = []
    x = y = 0; rowh = 0; W = 256
    imgs = []
    for c in range(32, 127):
        ch = chr(c)
        bbox = f.getbbox(ch)
        adv = int(round(f.getlength(ch)))
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            imgs.append((c, None, 0, 0, 0, 0, adv)); continue
        gw, gh = bbox[2] - bbox[0], bbox[3] - bbox[1]
        im = Image.new('L', (gw, gh), 0)
        ImageDraw.Draw(im).text((-bbox[0], -bbox[1]), ch, font=f, fill=255)
        imgs.append((c, im, gw, gh, bbox[0], bbox[1], adv))
    # pack
    placed = []
    for (c, im, gw, gh, xo, yo, adv) in imgs:
        if im is None:
            placed.append((c, 0, 0, 0, 0, 0, 0, adv)); continue
        if x + gw + 1 > W:
            x = 0; y += rowh + 1; rowh = 0
        placed.append((c, x, y, gw, gh, xo, yo, adv, im))
        x += gw + 1; rowh = max(rowh, gh)
    H = y + rowh + 1
    H = 1 << (H - 1).bit_length()
    atlas = Image.new('L', (W, H), 0)
    for p in placed:
        if len(p) == 9:
            atlas.paste(p[8], (p[1], p[2]))
    name = f's{size}'
    lines.append(f'static const Glyph {name}Glyphs[95] = {{')
    for p in placed:
        c, gx, gy, gw, gh, xo, yo, adv = p[:8]
        lines.append(f'    {{{gx}, {gy}, {gw}, {gh}, {xo}, {yo}, {adv}}}, // {c}')
    lines.append('};')
    data = atlas.tobytes()
    lines.append(f'static const uint8_t {name}Alpha[{len(data)}] = {{')
    for i in range(0, len(data), 32):
        lines.append('    ' + ','.join(str(b) for b in data[i:i+32]) + ',')
    lines.append('};')
    faces.append(f'    {{{size}, {ascent}, {W}, {H}, {name}Glyphs, {name}Alpha}},')
lines.append(f'static const Face faces[{len(SIZES)}] = {{')
lines += faces
lines.append('};')
lines.append(f'constexpr int faceCount = {len(SIZES)};')
lines.append('} // namespace swgb::font')
open(out, 'w').write('\n'.join(lines) + '\n')
print('wrote', out)
